#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""pipecat-quickstart - Pipecat Voice Agent

This bot uses a cascade pipeline: Speech-to-Text → LLM → Text-to-Speech

Generated by Pipecat CLI

Required AI services:
- Deepgram (Speech-to-Text)
- Openai (LLM)
- Cartesia (Text-to-Speech)

Run the bot using::

    uv run bot_dev.py
"""


import asyncio
import json
import os
import threading  # PeriodicSmartTurnAnalyzer
import time
import uuid
from concurrent.futures import Future as ConcurrentFuture  # PeriodicSmartTurnAnalyzer
from datetime import datetime

from pipecat.pipeline.runner import PipelineRunner
from pipecat.transports.base_output import BaseOutputTransport
from pipecat.transports.base_transport import BaseTransport
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.pipeline.task import PipelineParams, PipelineTask
from pipecat.frames.frames import (
    BotStartedSpeakingFrame,
    BotStoppedSpeakingFrame,
    FunctionCallInProgressFrame,
    InterimTranscriptionFrame,
    InterruptionFrame,
    LLMFullResponseEndFrame,
    LLMFullResponseStartFrame,
    LLMRunFrame,
    LLMTextFrame,
    MetricsFrame,
    TranscriptionFrame,
    TTSAudioRawFrame,
    TTSStartedFrame,
    TTSStoppedFrame,
    TTSTextFrame,
    UserStoppedSpeakingFrame,
    VADUserStartedSpeakingFrame,
    VADUserStoppedSpeakingFrame,
)
from pipecat.services.deepgram.stt import DeepgramSTTService
from loguru import logger
from pipecat.metrics.metrics import TurnMetricsData
from pipecat.observers.base_observer import BaseObserver, FramePushed
from pipecat.processors.frame_processor import FrameDirection
from pipecat.runner.types import SmallWebRTCRunnerArguments
from pipecat.pipeline.pipeline import Pipeline
from dotenv import load_dotenv
from pipecat.transports.smallwebrtc.transport import SmallWebRTCTransport
from pipecat.processors.aggregators.llm_response_universal import LLMContextAggregatorPair, LLMUserAggregatorParams
from pipecat.runner.types import RunnerArguments
from pipecat.services.openai.llm import OpenAILLMService
from pipecat.services.cartesia.tts import CartesiaTTSService
from pipecat.transports.smallwebrtc.connection import SmallWebRTCConnection
from pipecat.transports.base_transport import TransportParams
from pipecat.audio.vad.silero import SileroVADAnalyzer
from pipecat.audio.vad.vad_analyzer import VADParams
from pipecat.turns.user_turn_strategies import UserTurnStrategies
from pipecat.turns.user_stop.turn_analyzer_user_turn_stop_strategy import TurnAnalyzerUserTurnStopStrategy
from pipecat.audio.turn.smart_turn.local_smart_turn_v3 import LocalSmartTurnAnalyzerV3  # PeriodicSmartTurnAnalyzer
from pipecat.audio.turn.base_turn_analyzer import EndOfTurnState  # PeriodicSmartTurnAnalyzer

load_dotenv(override=True)

# ---------------------------------------------------------------------------
# Logging configuration
# ---------------------------------------------------------------------------
# Set ENABLE_LOGGING to False to suppress all conversation logging.
ENABLE_LOGGING = True
# Directory for per-session JSONL log files (created automatically if missing).
LOG_DIR = os.path.join(os.path.dirname(__file__), "logs")

# ---------------------------------------------------------------------------
# VAD tuning
# ---------------------------------------------------------------------------
# Duration of silence (seconds) before VAD confirms the user has stopped
# speaking. Lower values reduce turn-end latency at the cost of more false
# turn-ends on natural pauses. Default (framework): 0.2 s.
VAD_STOP_SECS: float = 0.2


# ---------------------------------------------------------------------------
# Periodic smart-turn analyzer (disabled)
# ---------------------------------------------------------------------------

class PeriodicSmartTurnAnalyzer(LocalSmartTurnAnalyzerV3):
    """LocalSmartTurnAnalyzerV3 that also runs inference at a fixed interval
    during active speech, not only at VAD-stop.

    Intermediate results are stored in a thread-safe list and drained by
    ConversationLogObserver, providing higher-resolution turn-probability logs
    without requiring an external streaming SDK.
    """

    def __init__(self, *, inference_interval_ms: int = 200, **kwargs):
        """Initialize the periodic smart-turn analyzer.

        Args:
            inference_interval_ms: Minimum gap in milliseconds between
                periodic inference runs during active speech. Defaults to 200.
            **kwargs: Additional arguments passed to LocalSmartTurnAnalyzerV3.
        """
        super().__init__(**kwargs)
        self._inference_interval_ms = inference_interval_ms
        self._last_periodic_time: float = 0.0
        self._pending_metrics: list[TurnMetricsData] = []
        self._pending_lock = threading.Lock()

    def append_audio(self, buffer: bytes, is_speech: bool) -> EndOfTurnState:
        state = super().append_audio(buffer, is_speech)
        now = time.time()
        if (
            is_speech
            and self._speech_triggered
            and (now - self._last_periodic_time) >= self._inference_interval_ms / 1000
        ):
            self._last_periodic_time = now
            # Snapshot the buffer so the background thread reads stable data
            buffer_snapshot = list(self._audio_buffer)
            future: ConcurrentFuture = self._executor.submit(
                self._process_speech_segment, buffer_snapshot
            )
            future.add_done_callback(self._on_periodic_done)
        return state

    def _on_periodic_done(self, future: ConcurrentFuture):
        try:
            _, metrics = future.result()
            if metrics is not None:
                with self._pending_lock:
                    self._pending_metrics.append(metrics)
        except Exception as e:
            logger.debug(f"PeriodicSmartTurnAnalyzer: inference error: {e}")

    def drain_metrics(self) -> list[TurnMetricsData]:
        """Pop and return all accumulated periodic metrics (thread-safe)."""
        with self._pending_lock:
            result = list(self._pending_metrics)
            self._pending_metrics.clear()
            return result

    def clear(self):
        super().clear()
        with self._pending_lock:
            self._pending_metrics.clear()
        self._last_periodic_time = 0.0


# ---------------------------------------------------------------------------
# Conversation logger
# ---------------------------------------------------------------------------

class ConversationLogObserver(BaseObserver):
    """Observer that writes a per-session JSONL raw event log (Tier 1).

    One JSON line is written per frame boundary with zero interpretation.
    High-level state reconstruction is done in post-processing.

    Event schema: ``{"ts_ns": <int>, "event": "<name>", ...payload}``

    The ``pipeline_started`` event carries ``wall_clock_unix_ns`` so that
    ``ts_ns`` offsets (pipeline-clock nanoseconds) can be anchored to real
    wall time during analysis.
    """

    def __init__(self, turn_analyzer: "PeriodicSmartTurnAnalyzer | None" = None):
        super().__init__()
        self._turn_analyzer = turn_analyzer
        self._polling_task: asyncio.Task | None = None
        self._session_id = uuid.uuid4().hex[:8]
        os.makedirs(LOG_DIR, exist_ok=True)
        ts_str = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"session_{ts_str}_{self._session_id}.jsonl"
        self._filepath = os.path.join(LOG_DIR, filename)
        # Line-buffered so each event is flushed immediately.
        self._file = open(self._filepath, "w", buffering=1, encoding="utf-8")
        # Deduplication: use frame.id (stable monotonic int) to process each frame once.
        self._seen_frame_ids: set[int] = set()
        # Track which TTS context_ids have emitted their first audio chunk.
        self._tts_first_audio_seen: set[str] = set()
        # Pipeline clock reference: time.monotonic_ns() - data.timestamp at first frame.
        self._mono_pipeline_origin: int = 0
        self._mono_pipeline_ready: bool = False
        logger.info(f"ConversationLogObserver: logging to {self._filepath}")

    # ------------------------------------------------------------------
    # BaseObserver interface
    # ------------------------------------------------------------------

    async def on_pipeline_started(self):
        wall_clock_ns = time.time_ns()
        self._log("pipeline_started", 0, wall_clock_unix_ns=wall_clock_ns, session_id=self._session_id)
        if self._turn_analyzer is not None:
            self._polling_task = asyncio.create_task(self._poll_periodic_metrics())

    async def _poll_periodic_metrics(self):
        """Drain PeriodicSmartTurnAnalyzer results and write turn_probability events."""
        try:
            while True:
                await asyncio.sleep(0.05)  # 20 Hz
                if self._turn_analyzer is None or not self._mono_pipeline_ready:
                    continue
                for m in self._turn_analyzer.drain_metrics():
                    ts = time.monotonic_ns() - self._mono_pipeline_origin
                    self._log(
                        "turn_probability",
                        ts,
                        probability=m.probability,
                        is_complete=m.is_complete,
                        e2e_ms=m.e2e_processing_time_ms,
                        source="periodic",
                    )
        except asyncio.CancelledError:
            pass

    async def on_push_frame(self, data: FramePushed):
        if data.direction != FrameDirection.DOWNSTREAM:
            return

        if not self._mono_pipeline_ready:
            self._mono_pipeline_origin = time.monotonic_ns() - data.timestamp
            self._mono_pipeline_ready = True

        frame_id = data.frame.id
        if frame_id in self._seen_frame_ids:
            return

        ts = data.timestamp
        frame = data.frame
        mark_as_seen = True

        if isinstance(frame, VADUserStartedSpeakingFrame):
            self._log("vad_started", ts)

        elif isinstance(frame, VADUserStoppedSpeakingFrame):
            self._log("vad_stopped", ts)

        elif isinstance(frame, UserStoppedSpeakingFrame):
            self._log("user_turn_end", ts)

        elif isinstance(frame, InterimTranscriptionFrame):
            self._log("stt_interim", ts, text=frame.text)

        elif isinstance(frame, TranscriptionFrame):
            self._log("stt_final", ts, text=frame.text)

        elif isinstance(frame, LLMFullResponseStartFrame):
            self._log("llm_started", ts)

        elif isinstance(frame, LLMFullResponseEndFrame):
            self._log("llm_stopped", ts)

        elif isinstance(frame, LLMTextFrame):
            self._log("llm_token", ts, text=frame.text)

        elif isinstance(frame, FunctionCallInProgressFrame):
            self._log("llm_function_call", ts, function_name=frame.function_name)

        elif isinstance(frame, TTSStartedFrame):
            self._log("tts_started", ts, context_id=frame.context_id)

        elif isinstance(frame, TTSStoppedFrame):
            self._log("tts_stopped", ts, context_id=frame.context_id)

        elif isinstance(frame, TTSTextFrame):
            if isinstance(data.source, BaseOutputTransport):
                # Log with correct timing: frame has passed through the output
                # transport, so this fires approximately at actual playback time.
                self._log("tts_text", ts, text=frame.text, context_id=frame.context_id,
                          aggregated_by=str(frame.aggregated_by))
            else:
                # First pass from TTS service — wait for the post-transport pass.
                mark_as_seen = False

        elif isinstance(frame, TTSAudioRawFrame):
            cid = frame.context_id
            if cid is not None and cid not in self._tts_first_audio_seen:
                self._tts_first_audio_seen.add(cid)
                self._log("tts_first_audio", ts, context_id=cid)

        elif isinstance(frame, BotStartedSpeakingFrame):
            self._log("bot_speaking_started", ts)

        elif isinstance(frame, BotStoppedSpeakingFrame):
            self._log("bot_speaking_stopped", ts)

        elif isinstance(frame, InterruptionFrame):
            self._log("interruption", ts)

        elif isinstance(frame, MetricsFrame):
            for item in frame.data:
                if isinstance(item, TurnMetricsData):
                    self._log(
                        "turn_probability",
                        ts,
                        probability=item.probability,
                        is_complete=item.is_complete,
                        e2e_ms=item.e2e_processing_time_ms,
                    )

        if mark_as_seen:
            self._seen_frame_ids.add(frame_id)

    async def cleanup(self):
        if self._polling_task is not None:
            self._polling_task.cancel()
            self._polling_task = None
        await super().cleanup()
        if self._file and not self._file.closed:
            self._file.flush()
            self._file.close()

    def _log(self, event: str, ts_ns: int, **payload):
        row = {"ts_ns": ts_ns, "event": event, **payload}
        self._file.write(json.dumps(row) + "\n")


async def run_bot(transport: BaseTransport):
    """Main bot logic."""
    logger.info("Starting bot")

    # Speech-to-Text service
    stt = DeepgramSTTService(api_key=os.getenv("DEEPGRAM_API_KEY") or "")

    # Text-to-Speech service
    tts = CartesiaTTSService(
            api_key=os.getenv("CARTESIA_API_KEY") or "",
            settings=CartesiaTTSService.Settings(
                voice=os.getenv("CARTESIA_VOICE_ID", "71a7ad14-091c-4e8e-a314-022ece01c121"),
            ),
        )


    # LLM service
    llm = OpenAILLMService(
            api_key=os.getenv("OPENAI_API_KEY") or "",
            settings=OpenAILLMService.Settings(
                model=os.getenv("OPENAI_MODEL", "gpt-4.1"),
                system_instruction="You are a helpful assistant in a voice conversation. Your responses will be spoken aloud, so avoid emojis, bullet points, or other formatting that can't be spoken. Respond to what the user said in a creative, helpful, and brief way.",
            ),
        )



    context = LLMContext()
    periodic_analyzer = PeriodicSmartTurnAnalyzer(inference_interval_ms=200)  # PeriodicSmartTurnAnalyzer
    user_aggregator, assistant_aggregator = LLMContextAggregatorPair(
        context,
        user_params=LLMUserAggregatorParams(
            vad_analyzer=SileroVADAnalyzer(params=VADParams(stop_secs=VAD_STOP_SECS)),
            user_turn_strategies=UserTurnStrategies(  # PeriodicSmartTurnAnalyzer
                stop=[TurnAnalyzerUserTurnStopStrategy(turn_analyzer=periodic_analyzer)]
            ),
        ),
    )


    


    # Pipeline - assembled from reusable components
    pipeline = Pipeline([
        transport.input(),

        stt,

        user_aggregator,

        llm,

        tts,

        
        transport.output(),

        
        assistant_aggregator,

    ])


    observers = []
    if ENABLE_LOGGING:
        observers.append(ConversationLogObserver(turn_analyzer=periodic_analyzer))

    task = PipelineTask(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
        ),
        observers=observers,
    )

    @task.rtvi.event_handler("on_client_ready")
    async def on_client_ready(rtvi):
        # Kick off the conversation
        context.add_message({"role": "user", "content": "Please introduce yourself."})
        await task.queue_frames([LLMRunFrame()])

    @transport.event_handler("on_client_connected")
    async def on_client_connected(transport, client):
        logger.info("Client connected")

    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        logger.info("Client disconnected")
        await task.cancel()




    runner = PipelineRunner(handle_sigint=False)

    await runner.run(task)


async def bot(runner_args: RunnerArguments):
    """Main bot entry point."""

    transport = None

    match runner_args:
        case SmallWebRTCRunnerArguments():
            webrtc_connection: SmallWebRTCConnection = runner_args.webrtc_connection

            transport = SmallWebRTCTransport(
                webrtc_connection=webrtc_connection,
                params=TransportParams(
                    audio_in_enabled=True,
                    audio_out_enabled=True,
                ),
            )
        case _:
            logger.error(f"Unsupported runner arguments type: {type(runner_args)}")
            return

    await run_bot(transport)


if __name__ == "__main__":
    from pipecat.runner.run import main

    main()